### ISSUE TITLE
Sending session_id in Cookies doesn't work

### ISSUE THREAD

**Issue by tillyr-cube48** [yezyilomo/odoo-rest-api#54]
Hi,

Thanks for your module this makes our work very simpler. I am working in Odoo 13

As mentioned, due to security purpose I sent the session_id in cookies but instead of returning the results I get Odoo Login page as the response (302 error - Redirection) for GET and DELETE Methods and Odoo session expired response for POST

could you please guide me on this issue?

**Comment by yezyilomo** [comment]
How are you sending your cookie?.

**Comment by meswapnilwagh** [comment]
I am also facing same issue, I am using postman to test the api, /auth route is working fine but with other route's I am facing same redirection issue and getting odoo login page as response.

Please find below postman request and Odoo logs

**PostmanRequest**
<img width="976" alt="Screen Shot 2020-12-03 at 2 17 47 PM" src="https://user-images.githubusercontent.com/4816238/100996310-572c5880-3572-11eb-9149-9a19d60c0daf.png">

**Odoo-Logs**

<img width="1792" alt="Screen Shot 2020-12-03 at 2 15 30 PM" src="https://user-images.githubusercontent.com/4816238/100996721-d588fa80-3572-11eb-8dc5-b94e82d57f1e.png">

`2020-12-03 10:07:50,550 1 DEBUG pls odoo.modules.registry: Multiprocess signaling check: [Registry - 2 -> 2] [Cache - 18 -> 18]
2020-12-03 10:07:50,566 1 INFO pls werkzeug: 172.27.0.1 - - [03/Dec/2020 10:07:50] "GET /api/res.users HTTP/1.1" 302 - 1 0.001 0.018
2020-12-03 10:07:50,582 1 DEBUG pls odoo.modules.registry: Multiprocess signaling check: [Registry - 2 -> 2] [Cache - 18 -> 18]
2020-12-03 10:07:50,601 1 INFO pls werkzeug: 172.27.0.1 - - [03/Dec/2020 10:07:50] "GET /web/login?redirect=http%3A%2F%2Flocalhost%3A8069%2Fapi%2Fres.users HTTP/1.1" 200 - 4 0.003 0.018`

Just to add more I am using postaman intercepter for sending cookies & working with odoo14

**Comment by jeffery9** [comment]
because nested a  `web/session/authenticate/` call  inside `/auth`, this is wrong for Odoo, there is 2 different sessions, each one is `auth =none`,  and` /auth ` return the  wrong one that has not be authenticated.

BTW.   `auth= none` should set uid = none in session, means the user in session has not login.

there have 2 solution, 
 1, dont use `/auth`, use `/web/session/authenticate`  instead
2, rewrite `/auth `, call odoo internal call `http.request.session.authenticate`  directly

good lucks.
